spring:
    datasource:
        datasource1:
          url: jdbc:sqlserver://localhost:1433;DatabaseName=springdemo1
          username: sa
          password: henlius@k905
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        datasource2:
            url: jdbc:sqlserver://localhost:1433;DatabaseName=springdemo2
            username: sa
            password: henlius@k905
            driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
mybatis-plus:
  global-config:
    db-config:
      capital-mode: true
logging:
  level:
    com.yangyu.demo.dao.source1: debug