spring:
    datasource:
        datasource1:
            url: jdbc:sqlserver://localhost:1433;DatabaseName=springdemo1
            username: sa
            password: henlius@k905
            driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        datasource2:
            url: jdbc:sqlserver://localhost:1433;DatabaseName=springdemo2
            username: sa
            password: henlius@k905
            driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jpa:
        database: sql-server
        hibernate:
            ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.SQLServer2012Dialect